api_test:
    path: /api/test
    controller: App\Controller\GeneralController::test

api_login:
    path: /api/login
    controller: App\Controller\GeneralController::login

api_trainer_clients:
    path: /api/trainer/clients
    controller: App\Controller\TrainerController::clients

api_trainer_exercices:
    path: /api/trainer/exercices
    controller: App\Controller\TrainerController::myExercices